### ISSUE TITLE
[FEATURE REQUEST] Choose between available cameras

### ISSUE THREAD

**Issue by NaturalDevCR** [symisc/faceio-npm#10]
It would be nice to have a selector with available cameras on device to select, or a button to switch between them... for example on a mobile phone you could let the camera switch between front or back camera.

Thanks in advance!.

**Comment by symisc** [comment]
You can already select the target camera during the Camera Authorization screen as shown on the attached image. This is browser specific as each vendor implement its own UI.

<img width="278" alt="camera-selection" src="https://github.com/symisc/faceio-npm/assets/4615920/8610258f-daaa-46dd-8a4d-e53160be875a">

**Comment by NaturalDevCR** [comment]
My request and suggestion is to be able to select between each available camera every time you start an enrollment, this would allow to enroll users with a phone in a much easier way.
