### ISSUE TITLE
No payload is beign saved when enrolling users

### ISSUE THREAD

**Issue by NaturalDevCR** [symisc/faceio-npm#11]
So, this wasn't happening before the last update... now when I enroll a person, the `payload`, its not beign saved...

This is my code:

```
console.log([
        data.uid,
        data.email,
        data.first_name,
        data.company,
        data.department
      ])
      
      //This console.log returns correctly strings... so everything should work!
```
<img width="472" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/0e843453-6451-483d-968a-4c820055b5cb">

```
faceio.enroll({
        enrollIntroTimeout: 5,
        userConsent: true,
        locale: 'es', // Default user locale
        payload: {
          /* The payload we want to associate with this particular user which is forwarded back to us upon future authentication of this user.*/
          'uid': data.uid,
          'email': data.email,
          'first_name': data.first_name,
          'company': data.company,
          'department': data.department,
        }
      })
```

Enrollment succeeds, but when authenticating, the payload returned is `null`.

Please help!

<img width="475" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/f598cb59-51cf-44e4-97f2-301e7f668ebf">

**Comment by NaturalDevCR** [comment]
I did a little more digging, and basically the error comes when any of the payload data strings have **diacritics** or **accents**... when this happens the whole `payload` turn `null`.

Please fix this... the `payload` should accept a string as is.

Also please specify in your documentation what data types are allowed in the payload.

**Comment by symisc** [comment]
**Payloads are JSON encoded before saved out, and transferred therefore you should Base64 any non ASCII string or BLOB data your want to associate with a particular user**. The [enroll parameters documentation](https://faceio.net/integration-guide#enroll_param) now already states that.
