### ISSUE TITLE
Error while establishing network connection with the target FACEIO processing node

### ISSUE THREAD

**Issue by NaturalDevCR** [symisc/faceio-npm#12]
I'm getting this error randomly at enrollment after the facial scan.

<img width="439" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/02427f8a-3db2-43bd-b798-fcc00c2ffd78">

My internet is working properly, and reloading the page works sometimes...

**Comment by symisc** [comment]
This error happen when your internet connection drops while establishing connection with the FACEIO node responsible for treating your request.

**Comment by NaturalDevCR** [comment]
Well, as I said my internet connection it’s rock solid, and this error “fixes” immediately when reloading the webpage… so… why do you mark it as completed without any further investigation?
