### ISSUE TITLE
Uncaught SyntaxError: Identifier 'fioErrCode' has already been declared (at fio.js:1:1)

### ISSUE THREAD

**Issue by NaturalDevCR** [symisc/faceio-npm#13]
Suddenly now this error is appearing, cache is cleared, i'm on NPM package versión: `1.0.9`, I haven't defined `fioErrCode` anywhere else, so this is an issue comming from the library.

`Uncaught SyntaxError: Identifier 'fioErrCode' has already been declared (at fio.js:1:1)`

**Comment by symisc** [comment]
**On your code**, you just have to rename the constant you defined to catch error codes to something else says: `const fioErrs = faceio.fetchAllErrorCodes(); `

**Comment by NaturalDevCR** [comment]
> **On your code**, you just have to rename the constant you defined to catch error codes to something else says: `const fioErrs = faceio.fetchAllErrorCodes(); `

I did it already, same error... you shouldn't close issues if they are not really complete... you gave me no chance to reply.

<img width="641" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/d2310eee-4616-4fcc-bd45-15ba97333836">

As you can see I made sure that nothing has the `fioErrCode` name in my project.

<img width="834" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/465a935f-47ee-4fd6-906c-111fea221bbe">

So... what's next?

**Comment by symisc** [comment]
Clear your cache and implement the instructions above. Next time, please raise your support ticket from the FACEIO Console.

Symisc Systems, SUARL

-----Original Message-----

**Comment by NaturalDevCR** [comment]
I did cleared my cache, and I DID implement the instructions above, actually your documentation instructions as it has been multiple times by now, it's wrong, or doesn't work as it's supossed to work.

PD: Next time, please don't close issues before you actually investigate them :)

**Comment by symisc** [comment]
Clearly the issue is on your code. You have redeclared the fioErrCode somewhere on your code. You have to search and rename that variable.

Finally, do not raise any future issues related to your proper code here.

Symisc Systems, SUARL

-----Original Message-----

**Comment by NaturalDevCR** [comment]
I'll raise all the issues I believe I have to because since day zero your library have been failing in so many basic stuff, and actually you don't accept your own errors, github issues exists to raise issues related with your library, which is what I've been doing here...

As I said, I did already checked the **only** place where this constant is declared, and actually showed you proof about that... you just don't want to investigate it at all... your support definitely it's one of the worst I've suffered ever.
