### ISSUE TITLE
Uncaught SyntaxError: Identifier 'fioErrCode' has already been declared

### ISSUE THREAD

**Issue by NaturalDevCR** [symisc/faceio-npm#14]
So, since you decided to delete my last Issue, I'm going to recapitulate again about this error... 

According to **your documentation**, when calling for the fioErrCodes which you did introduce in the last update... all we had to do was this:

`const fioErrCode = faceio.fetchAllErrorCodes();`

After my Issue over which you said that was my mistake, (even when I DID follow your documentation), you suggested to change the const name to `fioErrs`.

As a proof of that, you changed your `README` file yesterday, with this change:

`const fioErrs = faceio.fetchAllErrorCodes();`

So I did as you suggested, and this didn't work either, you claimed that somewhere **I redeclared** `fioErrCode` somewhere in my code... after digging for what whas happening I found out that your library can not be instanciated multiple times.

Instantiating your library multiple times leads to errors like this... this **SHOULD** be stated in your documentation... because it's more than normal that a complex web application will have multiple parts and possibly the need to instanciate a library multiple times, or instead you should not declare anything in the global scope of your library, which will lead to errors like the mentioned here.

By declaring a constant like fioErrCode in the global scope, the library assumes that it will be the only one using that specific identifier. However, when multiple instances of the library are instantiated, each instance tries to define the same constant, resulting in the "Identifier 'fioErrCode' has already been declared" error.

Ideally, libraries should define their constants within their own scopes, encapsulating them to prevent conflicts with other code in the project. This can be achieved through proper module bundling and encapsulation techniques.

This could potentially lead to errors with other libraries in the future, so hopefully you will choose to fix this in your library instead of forcing users to instantiate once.

Hopefully this time my issue will not be deleted, and this will be helpful for as feedback for your library.

**Comment by symisc** [comment]
_fio.js_ must be **instantiated a single time** from the CDN (internally, the NPM package already does that transparently for you). What you did yesterday is like instantiating jQuery multiple times on your SPA project. This will lead eventually to variable re-declaration errors.
