### ISSUE TITLE
Waiting timeout - Enrollment process is too slow

### ISSUE THREAD

**Issue by NaturalDevCR** [symisc/faceio-npm#2]
I don't understand why by default we have to wait this long in every part of the enrollment process (it also happens when authenticating)

As far as I understand, according to the documentation, I should be able to set the timeouts in the parameters of the function... but this makes no effect at all.

<img width="1152" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/b4e929c9-d0fb-4c63-b1b8-d8c588e8d420">

My enrollment function looks like this:

```
const enrollNewUser = async () => {
  await faceio.enroll({
    enrollIntroTimeout: 2,
    userConsent: false,
    locale: 'auto', // Default user locale
    payload: {
      /* The payload we want to associate with this particular user which is forwarded back to us upon future authentication of this user.*/
      uid: 123456, // Dummy ID linked to this particular user
      email: 'a@a.com',
      dni: '11111111',
      phone: '11111111',
      gender: 'male',
      birthday: '01/01/1000'
    }
  }).then(userInfo => {
    // User Successfully Enrolled!
    alert(
      `User Successfully Enrolled! Details:
           Unique Facial ID: ${userInfo.facialId}
           Enrollment Date: ${userInfo.timestamp}
           Gender: ${userInfo.details.gender}
           Age Approximation: ${userInfo.details.age}`
    );
    console.log(userInfo);
    // handle success, save the facial ID (userInfo.facialId), redirect to the dashboard...
  }).catch(errCode => {
    // Something went wrong during enrollment, log the failure
    handleError(errCode);
  })
}
```

**Comment by symisc** [comment]
Hello,

The minimal enrollment delay for the introduction window is **5 seconds** which is done via the `enrollIntroTimeout ` [parameter ](https://faceio.net/integration-guide#enroll_param) just like you did. If you set a value lower than 5 seconds (2 on your case), then the default timeout (12 seconds) shall be used instead. **New enrolled user have to understand the on-boarding process, this is the main reason we don't allow values lower than 5 seconds for the introduction window**.

Finally, you can refer to the `enroll()` method, parameters documentation at:  https://faceio.net/integration-guide#enroll_param for additional information.

**Comment by NaturalDevCR** [comment]
> Hello,
> 
> The minimal enrollment delay for the introduction window is **5 seconds** which is done via the `enrollIntroTimeout ` [parameter ](https://faceio.net/integration-guide#enroll_param) just like you did. If you set a value lower than 5 seconds (2 on your case), then the default timeout (12 seconds) shall be used instead. **New enrolled user have to understand the on-boarding process, this is the main reason we don't allow values lower than 5 seconds for the introduction window**.
> 
> Finally, you can refer to the `enroll()` method, parameters documentation at: https://faceio.net/integration-guide#enroll_param for additional information.

In my use case this is not needed and it actually makes my project very slow... 

I'm using faceio for an Timework Attendance for my company, the idea is that my employees will register the time when they arrive and when they leave, this whole waiting process and the "on boarding" process should be configurable by us!... this process is totally normal in every company which has this use case... it's terribly slow having to wait for all this timeouts specially if we don't have control over it.

Can you please consider this desition please?

**Comment by NaturalDevCR** [comment]
Nevermind, 5 seconds for the enrollment process it's ok, and I can see I can actually skip the user consent with another paramter, which makes the process easier... thanks!
