### ISSUE TITLE
Enroll and Authentication reset state

### ISSUE THREAD

**Issue by NaturalDevCR** [symisc/faceio-npm#3]
When authentication fails, if the authentication function is triggered again, the process will not start again:

<img width="1117" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/13b6cf29-2723-4134-958f-514ccb9a106e">

The same happens when Enrollment is completed or failed... right now it's necesary to reload the page to make it work again.

**Comment by symisc** [comment]
Hello,

_The Short Answer:_

You will need to call the  `faceio.restartSession()` method which let you perform another call to `enroll() `or `authenticate()` without reloading or refreshing the entire HTML page. 

Refer to the method documentation at: https://faceio.net/integration-guide#restart_sess

_The Long Answer:_

The introduced restartSession() [method](https://faceio.net/integration-guide#restart_sess) let you purge the current user session and request a new one. By default, sessions in FACEIO starts following the first call to the enroll() or authenticate() method whichever comes first, and are immutable. After successful call to this method, the old session is discarded, a new one is created, and you can perform another round of calls to enroll() or authenticate() for the same user without reloading (refreshing) the entire HTML page or relying on an external JavaScript function such as location.reload() to do so.

_Source_: https://blog.pixlab.io/2022/10/fiojs-190-released-with-face-duplication-prevention

**Comment by NaturalDevCR** [comment]
That made the trick
