### ISSUE TITLE
De-branding

### ISSUE THREAD

**Issue by NaturalDevCR** [symisc/faceio-npm#4]
Is there any way I can remove the faceio branding? I think paid users should be able to remove branding, specially when clicking on your logo takes away users from the main application to your website.

<img width="1474" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/eb94379b-0413-4c99-ba29-50535920f262">

Currently Widget customization is very poor in options... even when your documentation says it's possible to customize it.

**Comment by symisc** [comment]
Your end users are **in right to know** the service provider for your [facial authentication](https://faceio.net) operations; therefore the FACEIO logo cannot be hidden. You can already customize the widget, insert your own Logo which will be displayed on the top left corner region of the widget, set your privacy & terms of use URL, and so on via the Customization Tab of the _Application Manager_ on the [Console](https://console.faceio.net).

**Comment by NaturalDevCR** [comment]
But touching your logo take MY USERS away from MY APPLICATION to your website, one thing is you keep your brand visible I get that, but you should definitely not link to your website, specially when your logo is so huge.
