### ISSUE TITLE
Error handling not working

### ISSUE THREAD

**Issue by NaturalDevCR** [symisc/faceio-npm#5]
I'm trying to handle errors, the same way it's stated in the documentation, but when I log the error, all I get is a number:

<img width="376" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/2502a1ff-5e45-4dbc-86a3-83ceb8abb489">

Here is my code

```
async authenticateUser() {
      await faceio.authenticate({
        'locale': 'es' // Default user locale
      }).then((userData: any) => {
        console.log(userData)
        console.log('Success, user identified')
        console.log('Linked facial Id: ' + userData.facialId)
        console.log('Payload: ' + JSON.stringify(userData.payload))
      }).catch((errCode: any) => {
        console.error(errCode)
        this.handleError(errCode)
        // handle authentication failure. Visit:
        // https://faceio.net/integration-guide#error-codes
        // for the list of all possible error codes
      }).finally(() => {
        faceio.restartSession()
      })
    },
```

**Comment by symisc** [comment]
Well, what you got when an [enrollment ](https://faceio.net/integration-guide#enroll) or [authentication](https://faceio.net/integration-guide#authenticate) operation fails actually is an **integer error code** documented [here](https://faceio.net/integration-guide#error-codes). The promise is rejected with the corresponding error code. On your error handler callback, you have to make a big switch statement to isolate the **returned error code** just like the following gist: https://gist.github.com/symisc/34203d2811a39f2a871373abc6dd1ce9#file-faceio_integration_boilerplate-html-L95.

Please note that there is no `this.handleError(errCode)` method implementation, you have to **implement it yourself** on your code base. Please remove that statement from your code to get it working. Check the [gist](https://gist.github.com/symisc/34203d2811a39f2a871373abc6dd1ce9#file-faceio_integration_boilerplate-html-L95) above for a typical implementation of the  `handleError(errCode)`  function.

**Comment by NaturalDevCR** [comment]
Sorry but your documentation doesn't states anything about **integer error codes** and actually the link you provided with the gist, is exactly the same way I've implemented the switch statement to handle errors, but obviously, if whats returned is an integer, how is the switch statement gonna work if it's expecting something else?

Like where is defined `fioErrCode`? 

<img width="1059" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/0f31bc91-cea4-42e8-bf59-c928663edfbd">


This is not clear to me, and copying that code exactly as is, it's simply not working... please be more clear about it.

**Comment by NaturalDevCR** [comment]
> Well, what you got when an [enrollment ](https://faceio.net/integration-guide#enroll) or [authentication](https://faceio.net/integration-guide#authenticate) operation fails actually is an **integer error code** documented [here](https://faceio.net/integration-guide#error-codes). The promise is rejected with the corresponding error code. On your error handler callback, you have to make a big switch statement to isolate the **returned error code** just like the following gist: https://gist.github.com/symisc/34203d2811a39f2a871373abc6dd1ce9#file-faceio_integration_boilerplate-html-L95.
> 
> Please note that there is no `this.handleError(errCode)` method implementation, you have to **implement it yourself** on your code base. Please remove that statement from your code to get it working. Check the [gist](https://gist.github.com/symisc/34203d2811a39f2a871373abc6dd1ce9#file-faceio_integration_boilerplate-html-L95) above for a typical implementation of the `handleError(errCode)` function.

If what you mean is that we should asumme that the error list provided [here](https://faceio.net/integration-guide#error-codes) is listed in order meaning that the first one would be the errorCode 1, the second one the errorCode 2, and so on, that it's absolutely not clear, and you should either provide a better, cleaner and understandable documentation or change these errorCodes to their respective string names as many other API usually do.
