### ISSUE TITLE
Unclear Metrics

### ISSUE THREAD

**Issue by NaturalDevCR** [symisc/faceio-npm#6]
So, here's another not clear thing...

In the dashboard, specifically in the metrics dashboard, right now I only have 1 enrollment, but it shows multiple **unique facial id** like if there are more than just one added face... actually if I try to delete each one (using the GET method) it fails, except for the last one, which is the real one, once I delete the last record, all the other ones are deleted also... 

<img width="1521" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/e6d002ac-52d7-469a-b361-f4ef1988b5e0">

Aditionally please be more consise and clear with the documentation!.

**Comment by symisc** [comment]
These are static logs that are recorded for each new enrollment on your FACEIO application. When you delete a Facial ID via call to the DELETEFACIALID API endpoint, the logs are not modified at all, only the index count is decreased for each deletion you perform. You can even disable log collection entirety via the security tab of your Application Manager.

Symisc Systems, SUARL

-----Original Message-----
From: Josue ***@***.***>
To: symisc/faceio-npm ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Mon, 29 May 2023 6:15
Subject: [symisc/faceio-npm] Unclear Metrics (Issue #6)

So, here's another not clear thing...

In the dashboard, specifically in the metrics dashboard, right now I only have 1 enrollment, but it shows multiple **unique facial id** like if there are more than just one added face... actually if I try to delete each one (using the GET method) it fails, except for the last one, which is the real one, once I delete the last record, all the other ones are deleted also... 

<img width="1521" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/e6d002ac-52d7-469a-b361-f4ef1988b5e0">

Aditionally please be more consise and clear with the documentation!.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/symisc/faceio-npm/issues/6
