### ISSUE TITLE
Error Handling!!!

### ISSUE THREAD

**Issue by NaturalDevCR** [symisc/faceio-npm#7]
According to your last answer error codes are integers, and we should create a function to handle errors... you gave me a link to the documentation (which I have to say, it's very poor), in your documentation, there is NOTHING mentioning that errors are integers.

<img width="376" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/2502a1ff-5e45-4dbc-86a3-83ceb8abb489">

Here is my code

```
async authenticateUser() {
      await faceio.authenticate({
        'locale': 'es' // Default user locale
      }).then((userData: any) => {
        console.log(userData)
        console.log('Success, user identified')
        console.log('Linked facial Id: ' + userData.facialId)
        console.log('Payload: ' + JSON.stringify(userData.payload))
      }).catch((errCode: any) => {
        console.error(errCode)
        this.handleError(errCode)
        // handle authentication failure. Visit:
        // https://faceio.net/integration-guide#error-codes
        // for the list of all possible error codes
      }).finally(() => {
        faceio.restartSession()
      })
    },
```

I have my own handle error function like this:

```
export const handleError = (errCode: any) => {
  console.log('handleError: ', errCode)
  const errorMessages: { [key: number]: string } = {
    1: 'Access to the Camera stream was denied by the end user', // 'fioErrCode.PERMISSION_REFUSED'
    2: 'No faces were detected during the enroll or authentication process', // 'fioErrCode.NO_FACES_DETECTED'
    3: "Unrecognized face on this application's Facial Index", // 'fioErrCode.UNRECOGNIZED_FACE'
    4: 'Two or more faces were detected during the scan process', // 'fioErrCode.MANY_FACES'
    5: 'User enrolled previously (facial features already recorded). Cannot enroll again!', // 'fioErrCode.FACE_DUPLICATION'
    6: 'Presentation (Spoof) Attack (PAD) detected during the scan process', // 'fioErrCode.PAD_ATTACK'
    7: 'Calculated Facial Vectors of the user being enrolled do not match', // 'fioErrCode.FACE_MISMATCH'
    8: 'Wrong PIN code supplied by the user being authenticated', // 'fioErrCode.WRONG_PIN_CODE'
    9: 'Server side error', // 'fioErrCode.PROCESSING_ERR'
    10: 'Your application is not allowed to perform the requested operation (eg. Invalid ID, Blocked, Paused, etc.). Refer to the FACEIO Console for additional information', // 'fioErrCode.UNAUTHORIZED'
    11: 'Terms & Conditions set out by FACEIO/host application rejected by the end user', // 'fioErrCode.TERMS_NOT_ACCEPTED'
    12: 'The FACEIO Widget could not be (or is being) injected onto the client DOM', // 'fioErrCode.UI_NOT_READY'
    13: 'Client session expired. The first promise was already fulfilled but the host application failed to act accordingly', // 'fioErrCode.SESSION_EXPIRED'
    14: 'Ongoing operation timed out (eg, Camera access permission, ToS accept delay, Face not yet detected, Server Reply, etc.)', // 'fioErrCode.TIMEOUT'
    15: 'Widget instantiation requests exceeded for freemium applications. Does not apply for upgraded applications', // 'fioErrCode.TOO_MANY_REQUESTS'
    16: 'Origin or Referer HTTP request header is empty or missing', // 'fioErrCode.EMPTY_ORIGIN'
    17: 'Domain origin is forbidden from instantiating fio.js', // 'fioErrCode.FORBIDDDEN_ORIGIN'
    18: 'Country ISO-3166-1 Code is forbidden from instantiating fio.js', // 'fioErrCode.FORBIDDDEN_COUNTRY'
    19: 'Another authentication or enrollment session is in progress', // 'fioErrCode.SESSION_IN_PROGRESS'
    20: 'Error while establishing network connection with the target FACEIO processing node', // 'fioErrCode.NETWORK_IO'
  };

  alert(errorMessages[errCode] || 'Unknown error occurred');
};
```

As you can see I had to assume that the integer errorCodes are ordered the way it's listed in your documentation, since there is NOTHING indicating how this should be handled, for example in your documentation you state this in the boilerplate example:

```
switch (errCode) {
			case fioErrCode.PERMISSION_REFUSED:
				console.log("Access to the Camera stream was denied by the end user");
				break;
			case fioErrCode.NO_FACES_DETECTED:
				console.log("No faces were detected during the enroll or authentication process");
				break;
				
				//... the rest of the code
```

but `fioErrCode` is never defined in your boilerplate... also if it's true that the integers are ordered the way they are listed in your documentation (which I have to assume), I'm getting error codes like 21, which points to nothing!.... 

Please explain this... be consise, fix your documentation, and provide a reproducible link to see how should this work if possible!.

**Comment by symisc** [comment]
Hello,

`fioErrCode` is the **first object defined** on `fio.js `when you include the library via the [FACEIO CDN](https://cdn.faceio.net). **Are your integrating the library via CDN or using the NPM package**?

**Comment by NaturalDevCR** [comment]
> Hello,
> 
> 
> 
> `fioErrCode` is the **first object defined** on `fio.js `when you include the library via the [FACEIO CDN](https://cdn.faceio.net). **Are your integrating the library via CDN or using the NPM package**?

I’m using the NPM package.

**Comment by NaturalDevCR** [comment]
> Hello,
> 
> `fioErrCode` is the **first object defined** on `fio.js `when you include the library via the [FACEIO CDN](https://cdn.faceio.net). **Are your integrating the library via CDN or using the NPM package**?

So... how would it be implemented with the NPM package? I did check all the Vue and React articles mentioned in your site, and this is not explained at all.

**Comment by NaturalDevCR** [comment]
So, I had to check the CDN, unminify the code... and get this simple object that should be in the documentation by default:

const fioErrCode = {
        PERMISSION_REFUSED: 1,
        NO_FACES_DETECTED: 2,
        UNRECOGNIZED_FACE: 3,
        MANY_FACES: 4,
        PAD_ATTACK: 5,
        FACE_MISMATCH: 6,
        NETWORK_IO: 7,
        WRONG_PIN_CODE: 8,
        PROCESSING_ERR: 9,
        UNAUTHORIZED: 10,
        TERMS_NOT_ACCEPTED: 11,
        UI_NOT_READY: 12,
        SESSION_EXPIRED: 13,
        TIMEOUT: 14,
        TOO_MANY_REQUESTS: 15,
        EMPTY_ORIGIN: 16,
        FORBIDDDEN_ORIGIN: 17,
        FORBIDDDEN_COUNTRY: 18,
        UNIQUE_PIN_REQUIRED: 19,
        SESSION_IN_PROGRESS: 20,
        FACE_DUPLICATION: 21,
        MINORS_NOT_ALLOWED: 22,
    },
    
    For anyone needing this...

**Comment by symisc** [comment]
We are introducing the `fetchAllErrorCodes()` method for the **NPM Package** for much better error logging experience. This update is scheduled to be released in 72 hours on the official package manager.

**Comment by NaturalDevCR** [comment]
> We are introducing the `fetchAllErrorCodes()` method for the **NPM Package** for much better error logging experience. This update is scheduled to be released in 72 hours on the official package manager.

I'm getting a new error when enrolling an user:

```
TypeError: Assignment to constant variable.
    at faceIO._fillParameters (fio.js:1:20508)
    at fio.js:1:22052
    at new Promise (<anonymous>)
    at faceIO.enroll (fio.js:1:21829)
    at faceio.enroll (index.js:42:34)
    at Proxy.enrollNewUser (faceio-store.ts?t=1686248276642:49:20)
    at Proxy.<anonymous> (pinia.mjs:1366:30)
    at store.<computed> (pinia.mjs:916:40)
    at onSubmit (NewEmployee.vue:138:13)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
```

<img width="695" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/adf9d00e-fcd6-489d-9d81-3a6d53ee51d6">

This error isn't even handled with any errCode.

And as a result, I can't enroll users, it was working yesterday, actually this is the second time, enrollment stops working...

**Comment by symisc** [comment]
Our official [NPM package](https://www.npmjs.com/package/@faceio/fiojs) is now upgraded to **_fio.js_ V2.1** which implements [Age Verification & Minors Access Prevention](https://blog.pixlab.io/2023/06/age-verification-check-available-for-faceio-face-recognition).

Your error handler now should look like the following with the introduction of the  `faceio.fetchAllErrorCodes()` method:

```
function handleError(errCode){
   const fioErrCode = faceio.fetchAllErrorCodes();
    switch (errCode) {
    case fioErrCode.PERMISSION_REFUSED:
        console.log("Access to the Camera stream was denied by the end user");
    break;
    // etc...
    // Refer to the boilerplate at: https://gist.github.com/symisc/34203d2811a39f2a871373abc6dd1ce9
    // for the list of all possible error codes.
}
```

Please update to the latest NPM package release to get access to the latest features.

**Comment by NaturalDevCR** [comment]
> Our official [NPM package](https://www.npmjs.com/package/@faceio/fiojs) is now upgraded to **_fio.js_ V2.1** which implements [Age Verification & Minors Access Prevention](https://blog.pixlab.io/2023/06/age-verification-check-available-for-faceio-face-recognition).
> 
> Your error handler now should look like the following with the introduction of the `faceio.fetchAllErrorCodes()` method:
> 
> ```
> function handleError(errCode){
>    const fioErrCode = faceio.fetchAllErrorCodes();
>     switch (errCode) {
>     case fioErrCode.PERMISSION_REFUSED:
>         console.log("Access to the Camera stream was denied by the end user");
>     break;
>     // etc...
>     // Refer to the boilerplate at: https://gist.github.com/symisc/34203d2811a39f2a871373abc6dd1ce9
>     // for the list of all possible error codes.
> }
> ```
> 
> Please update to the latest NPM package release to get access to the latest features.

I don't see a v2.1 version in your NPM package...

The last one was actually 2 hours ago, version 1.0.9

<img width="1367" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/6709f7a7-66d7-49cb-974b-afd8801d559f">

**Comment by NaturalDevCR** [comment]
> > Our official [NPM package](https://www.npmjs.com/package/@faceio/fiojs) is now upgraded to **_fio.js_ V2.1** which implements [Age Verification & Minors Access Prevention](https://blog.pixlab.io/2023/06/age-verification-check-available-for-faceio-face-recognition).
> > Your error handler now should look like the following with the introduction of the `faceio.fetchAllErrorCodes()` method:
> > ```
> > function handleError(errCode){
> >    const fioErrCode = faceio.fetchAllErrorCodes();
> >     switch (errCode) {
> >     case fioErrCode.PERMISSION_REFUSED:
> >         console.log("Access to the Camera stream was denied by the end user");
> >     break;
> >     // etc...
> >     // Refer to the boilerplate at: https://gist.github.com/symisc/34203d2811a39f2a871373abc6dd1ce9
> >     // for the list of all possible error codes.
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please update to the latest NPM package release to get access to the latest features.
> 
> I don't see a v2.1 version in your NPM package...
> 
> The last one was actually 2 hours ago, version 1.0.9
> 
> <img alt="image" width="1367" src="https://user-images.githubusercontent.com/35145882/244590417-6709f7a7-66d7-49cb-974b-afd8801d559f.png">

Looking directly in the script, I can see version says 2.1

**
<img width="409" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/2892cb56-500c-455c-9b6f-9140ccc218a7">
**

Probably you did set the NPM package version wrong... but anyway, I'm still getting the same error message:

<img width="886" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/a975a88e-d86d-4496-85c9-c6ed6abfc1db">

**Comment by symisc** [comment]
The NPM package version is 1.0.9. fio.js, the core library is 2.1.

Symisc Systems, SUARL

-----Original Message-----

**Comment by symisc** [comment]
You have to clear your browser cache inorder to load the new version of fio.js.

Symisc Systems, SUARL

-----Original Message-----
